#!/usr/bin/env python3
"""Generate the compatibility matrix by measuring this desktop, right now.

The matrix is never hand-written. A hand-written one describes the toolkits its
author remembers, ages silently, and cannot be re-run to check whether it is
still true. This script probes every application on the accessibility bus and
writes what it found, stamped with the environment it found it in — because the
results are only true for that environment, and a matrix that does not say which
one is a matrix that will eventually lie.

Usage:
    python3 scripts/generate-compat-matrix.py --out docs/05-compatibility-matrix.md
"""

from __future__ import annotations

import argparse
import os
import platform
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "service"))

from desktop_service import capabilities, probe  # noqa: E402
from desktop_service.backends import atspi, loop, session_env, x11  # noqa: E402


def environment() -> dict[str, str]:
    """What this measurement is true of."""

    def command(*argv: str) -> str:
        try:
            return subprocess.run(argv, capture_output=True, text=True, timeout=5).stdout.strip()
        except Exception:
            return ""

    # Discovered rather than read from this process's environment: a script run
    # from an SSH shell inherits a terminal's idea of the session and would
    # otherwise stamp the matrix "session type: tty" while measuring GNOME.
    borrowed = session_env.discover()

    def described(name: str, default: str) -> str:
        return os.environ.get(name) or borrowed.get(name) or default

    return {
        "Measured": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        "Operating system": command("lsb_release", "-ds") or platform.platform(),
        "Kernel": platform.release(),
        "Desktop environment": borrowed.get("XDG_CURRENT_DESKTOP")
        or os.environ.get("XDG_CURRENT_DESKTOP", "unknown"),
        "Session type": borrowed.get("XDG_SESSION_TYPE") or described("XDG_SESSION_TYPE", "unknown"),
        "Display": x11.attached_display() or described("DISPLAY", "none"),
        "Python": platform.python_version(),
    }


def verdict(row: dict) -> str:
    """One word for what an agent can actually do with this application."""

    if row["windowCount"] == 0:
        return "no windows"
    # A GTK4 application puts its whole menu on the frame, so a handful of
    # actions is not the same surface as thirty. The threshold keeps Electron's
    # two-action frames out of a column that would imply they are driveable.
    if row["frameActionCount"] >= 10 and row["nodeCount"] <= 60:
        return "frame actions"
    if row["nodeCount"] > 60:
        return "walkable tree"
    if row["nodeCount"] > 1:
        return "shallow tree"
    return "opaque"


def render(rows: list[dict], env: dict[str, str]) -> str:
    lines = [
        "# Compatibility matrix",
        "",
        "Generated by `scripts/generate-compat-matrix.py`. Do not edit by hand —",
        "re-run it instead, and if a row surprises you, that is the point of it.",
        "",
        "## Environment",
        "",
        "| | |",
        "|---|---|",
    ]
    lines += [f"| {key} | {value} |" for key, value in env.items()]
    lines += [
        "",
        "## Applications on the accessibility bus",
        "",
        "| Application | Toolkit | Windows | Interfaces | Depth | Nodes | Collection | Frame actions | Actionable elements | Editable | Verdict |",
        "|---|---|---:|---:|---:|---:|---|---:|---:|---:|---|",
    ]
    for row in rows:
        collection = (
            "works"
            if row["collectionWorks"]
            else ("advertised only" if row["collectionAdvertised"] else "no")
        )
        depth = f"{row['reachableDepth']}{'+' if row['depthLimited'] else ''}"
        nodes = f"{row['nodeCount']}{'+' if row['nodeLimited'] else ''}"
        toolkit = row["toolkit"] + (f" {row['toolkitVersion']}" if row["toolkitVersion"] else "")
        lines.append(
            f"| {row['name']} | {toolkit or 'unknown'} | {row['windowCount']} | "
            f"{len(row['interfaces'])} | {depth} | {nodes} | {collection} | "
            f"{row['frameActionCount']} | {row['actionableElements']} | "
            f"{row['editableFields']} | {verdict(row)} |"
        )

    lines += ["", "## Column meanings", ""]
    lines += [
        "- **Interfaces** — how many AT-SPI interfaces the application advertises. Advertising",
        "  one is a claim; the Collection column is the only one that tests a claim.",
        "- **Depth / Nodes** — how far the tree could actually be followed. A trailing `+` means",
        f"  the probe's own bound stopped it ({probe.MAX_PROBE_DEPTH} levels, {probe.MAX_PROBE_NODES} nodes),",
        "  not the application running out of tree.",
        "- **Collection** — `advertised only` is the interesting failure: the application offers",
        "  the fast filtered query and then declines to serve it, which is why the manual walk",
        "  exists as a fallback rather than an optimisation.",
        "- **Frame actions** — named actions on the window itself. GTK4 applications put nearly",
        "  their whole menu here, which is why a near-empty element tree is not the same as an",
        "  undriveable application.",
        "- **Actionable elements** — elements *below* the frame that expose at least one action,",
        "  within the walk bounds above. Read it together with the previous column and never",
        "  instead of it: a toolkit puts its actions on the frame or on its widgets, and a zero in",
        "  one column is a statement about where they live, not about whether they exist.",
        "- **Editable** — elements an agent could type into.",
        "- **Verdict** — which of those surfaces an agent would actually drive this application by.",
        "",
        "## What this does not say",
        "",
        "AT-SPI exposes an application's *toolkit* version, never the application's own version,",
        "so no version column is offered rather than one being invented. Applications not running",
        "at measurement time are absent, not passing: the matrix is a photograph of a desktop, and",
        "an application nobody had open was never asked.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default="docs/05-compatibility-matrix.md")
    args = parser.parse_args()

    loop.get_loop().start()
    try:
        report = loop.call_on_loop(
            lambda: capabilities.build_report(
                probe_accessibility=atspi.probe_desktop,
                probe_capture=lambda: "",
                session_token="compat-matrix",
                observation_mode="poll",
            ),
            timeout=30.0,
        )
        tiers = {tier["id"]: tier for tier in report["tiers"]}
        if not tiers.get("accessibility", {}).get("available"):
            print("the accessibility bus is not available; nothing to measure", file=sys.stderr)
            return 1
        rows = loop.call_on_loop(lambda: [p.to_json() for p in probe.probe_all()], timeout=180.0)
    finally:
        loop.get_loop().stop()

    if not rows:
        print("no applications on the accessibility bus", file=sys.stderr)
        return 1

    out = ROOT / args.out
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render(rows, environment()))
    print(f"{out}: {len(rows)} applications measured")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
