/**
 * What is talking to this hub, answered from what the hub already knows.
 *
 * The ruling (docs/10-distribution-and-dashboard.md) is one hub that is both the
 * dashboard and the first client, with other clients pairing to it. This route
 * is where that list becomes visible. It reports three kinds of thing and
 * invents none of them:
 *
 *   this machine — the hub is running here, so it is always present and never
 *                  removable. There is no state to read; the fact that this
 *                  request was answered is the fact.
 *   the widget   — connected or not, counted off the one loopback event socket
 *                  a face actually holds. No socket, no row-with-a-stale-name:
 *                  the row says it is not connected, which is the truth.
 *   paired       — nothing, today. Pairing is #35's QR flow and it carries its
 *                  own security story; until it lands there is no registry to
 *                  read and the honest answer is an empty list with a reason.
 *
 * Two things this deliberately does not do. It mints no device identifier that
 * this product did not already generate — no hostname, no MAC, no address, no
 * probe of the network — because a page that answers "what is connected" must
 * not become the thing that fingerprints the machine it runs on. And it is
 * read-only: the only mutation the issue admits is revocation, and there is
 * nothing to revoke until there is something to pair.
 */

import { Hono } from "hono";

export const DEVICES_PATH = "/api/devices";

/** The surfaces this hub has a word for. Closed, like every other vocabulary here. */
export const DEVICE_KINDS = ["hub", "widget"] as const;
export type DeviceKind = (typeof DEVICE_KINDS)[number];

export type DeviceView = {
  kind: DeviceKind;
  /**
   * The display name, generated by this product rather than read off the
   * machine. "This machine" is a true thing to call the computer a person is
   * sitting at; its hostname is a fact about their network.
   */
  name: string;
  connected: boolean;
  /** The line under the name, phrased for a person rather than for a log. */
  detail: string;
  /** Whether the page may offer a revoke control. The hub is never removable. */
  removable: boolean;
};

export type DevicesView = {
  /** This machine first, always. Then whatever else is actually attached. */
  devices: DeviceView[];
  /**
   * Whether this hub can pair another device, and why not when it cannot.
   *
   * Shaped like the voice and orb blocks in /api/health on purpose: a surface
   * that is off says so with a reason a person can act on, and the page repeats
   * it instead of offering a button that cannot work.
   */
  pairing: { enabled: false; reason: string };
};

export type DevicesMount = {
  /**
   * How many faces hold the event socket right now, asked per request rather
   * than captured at boot: a widget that started after the hub did is exactly
   * the case this page exists to show.
   */
  faces: () => number;
};

const HUB_DETAIL = "The hub is running here. This is the machine the agent acts on.";

const NO_WIDGET =
  "No widget is connected to this hub right now. Start it and this row will say so.";

const NO_PAIRING =
  "Pairing another device arrives with the phone client. Until then, this hub serves the machine it runs on.";

export function buildDevicesApp(mount: DevicesMount): Hono {
  const app = new Hono();

  app.get(DEVICES_PATH, (c) => {
    const faces = mount.faces();
    return c.json<DevicesView>({
      devices: [
        {
          kind: "hub",
          name: "This machine",
          connected: true,
          detail: HUB_DETAIL,
          removable: false,
        },
        {
          kind: "widget",
          name: "The orb widget",
          connected: faces > 0,
          detail: faces > 0 ? describeFaces(faces) : NO_WIDGET,
          // A widget is not a paired client — it is this machine drawing its own
          // face over a loopback socket. Revoking it would mean closing a window,
          // which is the window's business.
          removable: false,
        },
      ],
      pairing: { enabled: false, reason: NO_PAIRING },
    });
  });

  return app;
}

/**
 * More than one face is a normal state, not an error: the widget and the orb
 * page in a browser tab are two faces of the same hub, and both are honest.
 */
function describeFaces(count: number): string {
  return count === 1
    ? "Connected, over this machine's loopback event socket."
    : `Connected, over ${count} loopback event sockets on this machine.`;
}
